spring:
  security:
    oauth2:
     resourcesserver:
      jwt :
        issuer-uri : "http://localhost:909/realms/micro-services"

  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service